# -*- coding: utf-8 -*-
"""spendDNA_Kiruthick Vasan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qlBG8KFq3LRy6Uimhk7PHMG-8LRWfHgQ

# SpendDNA - Financial Transaction Analysis

# Name : Kiruthick Vasan R

# Batch : DADS June Batch

# Date : 05/07/2026

# Industry-Graded Minor Project


# This project analyzes six months of financial transaction data using Python, NumPy, and Pandas.


Objective



1.   Clean raw banking transaction data
2.   Extract vendor names




1.   Categorize expenses
2.   Analyze monthly spending

1.   Detect anomalies
2.  Identify spending archetypes


1.   Generate a complete SpendDNA report

# Feature 1: Transaction Parser
"""

# AI-assisted: Library import and notebook setup

import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 20)

print("Libraries Imported Successfully")

# AI-assisted: Load dataset

from google.colab import files

uploaded = files.upload()

import pandas as pd
import numpy as np

df = pd.read_csv("Data_set_for_DADS_June.csv")

df.head()

df.sample(5)

df.columns

df.dtypes

df['Amount'] = (
    df['Amount']
      .astype(str)
      .str.replace('₹','', regex=False)
      .str.replace('Rs.','', regex=False)
      .str.replace(',','', regex=False)
      .str.strip()
)

df['Amount'] = pd.to_numeric(df['Amount'], errors='coerce')

df['Amount'].head()

df['Amount'].isnull().sum()

df['Type'] = df['Type'].replace({
    'DR':'debit',
    'Debit':'debit',
    'CR':'credit',
    'Credit':'credit'
})

df['Type'] = df['Type'].str.lower()

df['Type'].value_counts()

print("Before:", df.shape)

df = df.drop_duplicates()

print("After :", df.shape)

df.isnull().sum()

df_clean = df.copy()

"""Feature 2: Vendor Extractor"""

df_clean['Description'].unique()

def extract_vendor(description):

    description = str(description).upper()

    for vendor, keywords in vendor_dict.items():

        for keyword in keywords:

            if keyword in description:
                return vendor

    return "Uncategorised"

vendor_dict = {

    # Food Delivery
    "Swiggy": [
        "SWIGGY", "BUNDL", "SWIGGY*ORDER", "POS SWIGGY"
    ],

    "Zomato": [
        "ZOMATO", "ZOMATO MEDIA"
    ],

    # Quick Commerce
    "Blinkit": [
        "BLINKIT", "GROFERS"
    ],

    "Instamart": [
        "INSTAMART"
    ],

    "Zepto": [
        "ZEPTO", "KIRANAKART"
    ],

    "DMart": [
        "DMART", "AVENUE SUPERMARTS"
    ],

    # Shopping
    "Amazon": [
        "AMAZON", "AMZN"
    ],

    "Flipkart": [
        "FKART", "FLIPKART"
    ],

    "Nykaa": [
        "FSN", "NYKAA"
    ],

    # Cafes
    "Starbucks": [
        "STARBUCKS", "TATA STARBUCKS"
    ],

    "Third Wave Coffee": [
        "THIRDWAVE", "THIRD WAVE", "TWC INDIA"
    ],

    "Cafe Coffee Day": [
        "CCD", "COFFEE DAY"
    ],

    # Restaurants
    "Empire Restaurant": [
        "EMPIRE"
    ],

    "Meghana Foods": [
        "MEGHANA"
    ],

    "Truffles": [
        "TRUFFLES"
    ],

    "Restaurant": [
        "RESTAURANT", "DINEOUT"
    ],

    # Transport
    "Uber": [
        "UBER", "ANI TECHNOLOGIES"
    ],

    "Rapido": [
        "RAPIDO", "ROPPEN"
    ],

    "BMTC": [
        "BMTC", "TUMMOC"
    ],

    # Fuel
    "Indian Oil": [
        "IOC", "INDIAN OIL"
    ],

    "HP Petrol": [
        "HP PETROL"
    ],

    "BPCL": [
        "BPCL"
    ],

    # Entertainment
    "BookMyShow": [
        "BMS", "BIGTREE"
    ],

    # Utilities
    "BESCOM": [
        "BESCOM", "ELEC"
    ],

    "BWSSB": [
        "BWSSB"
    ],

    "VI": [
        "VI", "VODAFONE"
    ],

    # Salary
    "Salary": [
        "SALARY"
    ],

    # Rent
    "Rent": [
        "LANDLORD", "RENT"
    ],

    # ATM
    "Cash Withdrawal": [
        "ATM-WDL", "ATM"
    ],

    # Personal Transfers
    "P2P Transfer": [
        "AMAN", "NEHA", "SNEHA",
        "KARAN", "VIKAS"
    ]
}

def extract_vendor(description):

    description = str(description).upper()

    for vendor, keywords in vendor_dict.items():

        for keyword in keywords:

            if keyword in description:
                return vendor

    return "Uncategorised"

df_clean["vendor_clean"] = df_clean["Description"].apply(extract_vendor)

df_clean[["Description","vendor_clean"]].head(20)

df_clean["vendor_clean"].value_counts()

df_clean[df_clean["vendor_clean"]=="Uncategorised"]["Description"].value_counts()

"""Feature 3 – Category Tagger"""

category_dict = {

    # Food Delivery
    "Swiggy": "Food Delivery",
    "Zomato": "Food Delivery",

    # Quick Commerce
    "Blinkit": "Quick Commerce",
    "Instamart": "Quick Commerce",
    "Zepto": "Quick Commerce",

    # Groceries
    "DMart": "Groceries",
    "Reliance Fresh": "Groceries",

    # Cafe
    "Starbucks": "Cafe",
    "Third Wave Coffee": "Cafe",
    "Cafe Coffee Day": "Cafe",

    # Restaurants
    "Empire Restaurant": "Restaurants",
    "Meghana Foods": "Restaurants",
    "Truffles": "Restaurants",
    "Restaurant": "Restaurants",

    # E-commerce
    "Amazon": "E-commerce",
    "Flipkart": "E-commerce",
    "Myntra": "E-commerce",
    "Nykaa": "E-commerce",

    # Transport
    "Uber": "Transport",
    "Ola": "Transport",
    "Rapido": "Transport",
    "BMTC": "Transport",

    # Fuel
    "Indian Oil": "Fuel",
    "HP Petrol": "Fuel",
    "BPCL": "Fuel",

    # Entertainment
    "BookMyShow": "Entertainment",

    # Utilities
    "BESCOM": "Utilities",
    "BWSSB": "Utilities",
    "VI": "Utilities",

    # Investments
    "Zerodha": "Investments",

    # Salary
    "Salary": "Income",

    # Rent
    "Rent": "Rent",

    # Cash
    "Cash Withdrawal": "Cash Withdrawal",

    # Personal
    "P2P Transfer": "Personal Transfer"
}

df_clean["category"] = df_clean["vendor_clean"].map(category_dict)

df_clean["category"] = df_clean["category"].fillna("Others")

df_clean["category"].value_counts()

df_clean[["vendor_clean", "category"]].head(20)

df_clean.head()

"""Feature 4 - Spending Overview"""

total_credits = df_clean[df_clean["Type"]=="credit"]["Amount"].sum()

print("Total Credits : ₹{:,.2f}".format(total_credits))

total_debits = df_clean[df_clean["Type"]=="debit"]["Amount"].sum()

print("Total Debits : ₹{:,.2f}".format(total_debits))

net_savings = total_credits - total_debits

print("Net Savings : ₹{:,.2f}".format(net_savings))

savings_rate = (net_savings / total_credits) * 100

print("Savings Rate : {:.2f}%".format(savings_rate))

print("Total Transactions :", len(df_clean))

print("Unique Vendors :", df_clean["vendor_clean"].nunique())

top_categories = (
    df_clean[df_clean["Type"]=="debit"]
    .groupby("category")["Amount"]
    .sum()
    .sort_values(ascending=False)
)

top_categories.head()

top_vendors = (
    df_clean[df_clean["Type"]=="debit"]
    .groupby("vendor_clean")["Amount"]
    .sum()
    .sort_values(ascending=False)
)

top_vendors.head()

df_clean["vendor_clean"].value_counts().head()

print("="*60)
print("SPENDDNA - EXECUTIVE SUMMARY")
print("="*60)

print(f"Total Credits      : ₹{total_credits:,.2f}")
print(f"Total Debits       : ₹{total_debits:,.2f}")
print(f"Net Savings        : ₹{net_savings:,.2f}")
print(f"Savings Rate       : {savings_rate:.2f}%")
print(f"Transactions       : {len(df_clean)}")
print(f"Unique Vendors     : {df_clean['vendor_clean'].nunique()}")

print("="*60)

print("\nTop 5 Categories")
print(top_categories.head())

print("\nTop 5 Vendors")
print(top_vendors.head())

"""Feature 5 - Monthly Trend Analysis"""

df_clean["Date"].dtype

df_clean["Date"] = pd.to_datetime(
    df_clean["Date"],
    errors="coerce",
    dayfirst=True
)

df_clean["Date"].dtype

df_clean["month"] = df_clean["Date"].dt.month

print(df_clean["Date"].dtype)

print(df_clean[["Date"]].head())

df_clean["month"] = df_clean["Date"].dt.month

df_clean["Date"] = pd.to_datetime(
    df_clean["Date"],
    errors="coerce",
    dayfirst=True
)

df_clean["Date"].dtype

df_clean["Date"].head(10)

df_clean.columns

"""# Feature 6 - Time-of-Day Analysis"""

df_clean["hour"] = df_clean["Time"].str[:2].astype(int)

df_clean[["Time","hour"]].head()

hourly_spending = (
    df_clean[df_clean["Type"]=="debit"]
    .groupby("hour")["Amount"]
    .sum()
    .sort_index()
)

hourly_spending

peak_hour = hourly_spending.idxmax()

peak_amount = hourly_spending.max()

print("Peak Spending Hour :", peak_hour)
print("Amount Spent : ₹{:,.2f}".format(peak_amount))

late_night = df_clean[
    (df_clean["hour"] >= 21) &
    (df_clean["Type"] == "debit")
]

print("Late Night Transactions :", len(late_night))
print("Late Night Spending : ₹{:,.2f}".format(late_night["Amount"].sum()))

late_food = df_clean[
    (df_clean["hour"] >= 21) &
    (df_clean["category"] == "Food Delivery")
]

print(late_food[["Description", "Amount", "Time"]])

hour_category = pd.pivot_table(
    df_clean[df_clean["Type"]=="debit"],
    values="Amount",
    index="hour",
    columns="category",
    aggfunc="sum",
    fill_value=0
)

hour_category

df_clean.columns

"""Feature 7 - Anomaly Detection"""

category_mean = df_clean.groupby("category")["Amount"].transform("mean")
category_mean.head()

category_std = df_clean.groupby("category")["Amount"].transform("std")
category_std.head()

df_clean["z_score"] = (
    (df_clean["Amount"] - category_mean)
    / category_std
)

df_clean["z_score"] = df_clean["z_score"].round(2)

df_clean.head()

anomalies = df_clean[df_clean["z_score"] > 3]

anomalies

anomalies = anomalies.sort_values(
    by="z_score",
    ascending=False
)

anomalies.head(10)

print("="*60)
print("ANOMALY DETECTION REPORT")
print("="*60)

print("Total Anomalies :", len(anomalies))

print("\nTop 10 Anomalies")

print(
    anomalies[
        [
            "Date",
            "Description",
            "vendor_clean",
            "category",
            "Amount",
            "z_score"
        ]
    ].head(10)
)

"""# Feature 8 - Spending Archetype Detection"""

category_spend = (
    df_clean[df_clean["Type"] == "debit"]
    .groupby("category")["Amount"]
    .sum()
)

category_spend

total_spend = category_spend.sum()

print("Total Debit Spend : ₹{:,.2f}".format(total_spend))

category_percent = (
    category_spend / total_spend
) * 100

category_percent = category_percent.round(2)

category_percent

archetypes = []

if category_percent.get("Food Delivery", 0) > 20:
    archetypes.append("🍔 THE FOODIE")

if category_percent.get("Quick Commerce", 0) > 15:
    archetypes.append("⚡ THE QUICK COMMERCE USER")

if category_percent.get("E-commerce", 0) > 15:
    archetypes.append("🛍️ THE SHOPAHOLIC")

if category_percent.get("Investments", 0) > 10:
    archetypes.append("📈 THE INVESTOR")

if category_percent.get("Transport", 0) > 12:
    archetypes.append("🚕 THE TRAVELLER")

if category_percent.get("Cafe", 0) > 8:
    archetypes.append("☕ THE CAFE LOVER")

if category_percent.get("Restaurants", 0) > 10:
    archetypes.append("🍽️ THE RESTAURANT EXPLORER")

if category_percent.get("Entertainment", 0) > 5:
    archetypes.append("🎬 THE ENTERTAINER")

food_orders = df_clean[df_clean["category"] == "Food Delivery"]

late_food = food_orders[food_orders["hour"] >= 21]

if len(food_orders) > 0:
    late_percent = (len(late_food) / len(food_orders)) * 100
else:
    late_percent = 0

print("Late Night Food Orders :", round(late_percent,2), "%")

if late_percent > 50:
    archetypes.append("🌙 THE LATE NIGHT SNACKER")

if net_savings < 0:
    archetypes.append("💸 THE YOLO SPENDER")

print("="*60)
print("SPENDING ARCHETYPES")
print("="*60)

for item in archetypes:
    print(item)

"""Final SpendDNA Report"""

print("="*70)
print("                SPENDDNA REPORT")
print("="*70)

print(f"Total Credits      : ₹{total_credits:,.2f}")
print(f"Total Debits       : ₹{total_debits:,.2f}")
print(f"Net Savings        : ₹{net_savings:,.2f}")
print(f"Savings Rate       : {savings_rate:.2f}%")
print(f"Transactions       : {len(df_clean)}")
print(f"Unique Vendors     : {df_clean['vendor_clean'].nunique()}")

print("\nTOP 5 CATEGORIES")
print(top_categories.head())

print("\nTOP 5 VENDORS")
print(top_vendors.head())

print("\nSPENDING ARCHETYPES")
for item in archetypes:
    print(item)

print("\nTOP ANOMALIES")
print(
    anomalies[
        ["Description", "Amount", "z_score"]
    ].head(5)
)

print("="*70)
print("END OF REPORT")
print("="*70)